[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200


lib_deps = 
	Wire
    SPI
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit MLX90614 Library @ ^2.1.6
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2


build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1