var searchData=
[
  ['sensor_20data_0',['Access Sensor Data',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md21',1,'']]],
  ['sensor_20not_20found_1',['Sensor Not Found',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md30',1,'']]],
  ['sensor_20specifications_2',['Sensor Specifications',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md23',1,'']]],
  ['sensorreadings_3',['SensorReadings',['../struct_sensor_readings.html',1,'']]],
  ['sensors_4',['1. Include All Sensors',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md14',1,'']]],
  ['sensors_20max30105_5',['Pulse Oximeter &amp;amp; Heart Rate (&lt;span class=&quot;tt&quot;&gt;Sensors/MAX30105/&lt;/span&gt;)',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md4',1,'']]],
  ['sensors_20mlx90614_6',['Non-Contact Thermometer (&lt;span class=&quot;tt&quot;&gt;Sensors/MLX90614/&lt;/span&gt;)',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md5',1,'']]],
  ['sensors_20mpu6050_7',['6-Axis IMU (&lt;span class=&quot;tt&quot;&gt;Sensors/MPU6050/&lt;/span&gt;)',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md6',1,'']]],
  ['sensors_20oled_8',['Display Driver (&lt;span class=&quot;tt&quot;&gt;Sensors/OLED/&lt;/span&gt;)',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md7',1,'']]],
  ['sensors_20on_20i2c_20bus_9',['Sensors on I2C Bus',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md11',1,'']]],
  ['sensors_2eh_10',['Sensors.h',['../_sensors_8h.html',1,'']]],
  ['sensorutils_2ecpp_11',['SensorUtils.cpp',['../_sensor_utils_8cpp.html',1,'']]],
  ['sensorutils_2eh_12',['SensorUtils.h',['../_sensor_utils_8h.html',1,'']]],
  ['sequence_20in_20loop_13',['Update Sequence (in loop())',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md53',1,'']]],
  ['serial_20monitor_14',['Serial Monitor',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md44',1,'']]],
  ['setup_15',['3. Initialize in Setup',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md16',1,'']]],
  ['smartaidkit_20embedded_20health_20monitoring_20system_16',['SmartAidKit - Embedded Health Monitoring System',['../index.html',1,'']]],
  ['specifications_17',['Sensor Specifications',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md23',1,'']]],
  ['spo2_20values_18',['High Heart Rate / SpO2 Values',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md31',1,'']]],
  ['spo2_5falgorithm_2ecpp_19',['spo2_algorithm.cpp',['../spo2__algorithm_8cpp.html',1,'']]],
  ['spo2_5falgorithm_2eh_20',['spo2_algorithm.h',['../spo2__algorithm_8h.html',1,'']]],
  ['ssd1306_20oled_21',['SSD1306 (OLED)',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md27',1,'']]],
  ['ssd1306_20oled_20display_22',['SSD1306 OLED Display',['../group___o_l_e_d___group.html',1,'']]],
  ['structure_23',['Project Structure',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md1',1,'']]],
  ['supply_5fvoltage_5fmax_24',['SUPPLY_VOLTAGE_MAX',['../driver__mpu6050_8c.html#a68eba8b601afe11f1b871d944976c035',1,'driver_mpu6050.c']]],
  ['supply_5fvoltage_5fmax_5fv_25',['supply_voltage_max_v',['../structmpu6050__info__s.html#a279d6c6d64a3a6728f5b943b7a176fd2',1,'mpu6050_info_s']]],
  ['supply_5fvoltage_5fmin_26',['SUPPLY_VOLTAGE_MIN',['../driver__mpu6050_8c.html#aac8d8cbd899667d609787ef4cf37054d',1,'driver_mpu6050.c']]],
  ['supply_5fvoltage_5fmin_5fv_27',['supply_voltage_min_v',['../structmpu6050__info__s.html#a8f8aff896caecd4dccaa31327a511ae4',1,'mpu6050_info_s']]],
  ['support_28',['Support',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md55',1,'']]],
  ['system_29',['SmartAidKit - Embedded Health Monitoring System',['../index.html',1,'']]],
  ['system_20core_30',['Core System (&lt;span class=&quot;tt&quot;&gt;Core/&lt;/span&gt;)',['../E:/Projects/Embedded/Dr. Riyad/SmartAidKit/SmartAidKit/README.md#autotoc_md3',1,'']]]
];
